export const APP_SET_EDIT_DATA = 'APP_SET_EDIT_DATA';

export const INPUT_IMAGE_CHANGE = 'INPUT_IMAGE_CHANGE';
export const INPUT_SUBMIT = 'INPUT_SUBMIT';
export const INPUT_TEXT_CHANGE = 'INPUT_TEXT_CHANGE';

export const EDIT_REQUEST_DATA = 'EDIT_REQUEST_DATA';
export const EDIT_GET_DATA = 'EDIT_GET_DATA';
export const EDIT_SET_DATA = 'EDIT_SET_DATA';
export const EDIT_CONFIRM = 'EDIT_CONFIRM';
export const EDIT_CANCEL = 'EDIT_CANCEL';
export const EDIT_TITLE_CHANGE = 'EDIT_TITLE_CHANGE';
export const EDIT_DESCRIPTION_CHANGE = 'EDIT_DESCRIPTION_CHANGE';

export const ITEM_VOTE_UP = 'ITEM_VOTE_UP';
export const ITEM_VOTE_DOWN = 'ITEM_VOTE_DOWN';
export const ITEM_DELETE = 'ITEM_DELETE';

export const LIST_SORT_NEWEST = 'LIST_SORT_NEWEST';
export const LIST_SORT_VOTES = 'LIST_SORT_VOTES';

export const COMMENT_CHANGE = 'COMMENT_CHANGE';
export const COMMENT_SUBMIT = 'COMMENT_SUBMIT';

export const COMMENT_LIST_SET_DATA = 'COMMENT_LIST_SET_DATA';
